theme: jekyll-theme-minimal
title: Worldreader Query Data Project
description: A Capstone Project for the Data Science and Big Data course at Universitat de Barcelona. Project Members: Cary Lewis, Aina Pascual, Patricia Araguz and Enrique Rodr√≠guez
